<?php

namespace ContainerROGiq9o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_TranslationUpdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.translation_update' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\TranslationUpdateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Symfony\Component\Translation\Writer\TranslationWriter();
        $a->addDumper('php', new \Symfony\Component\Translation\Dumper\PhpFileDumper());
        $a->addDumper('xlf', new \Symfony\Component\Translation\Dumper\XliffFileDumper());
        $a->addDumper('po', new \Symfony\Component\Translation\Dumper\PoFileDumper());
        $a->addDumper('mo', new \Symfony\Component\Translation\Dumper\MoFileDumper());
        $a->addDumper('yml', new \Symfony\Component\Translation\Dumper\YamlFileDumper());
        $a->addDumper('yaml', new \Symfony\Component\Translation\Dumper\YamlFileDumper('yaml'));
        $a->addDumper('ts', new \Symfony\Component\Translation\Dumper\QtFileDumper());
        $a->addDumper('csv', new \Symfony\Component\Translation\Dumper\CsvFileDumper());
        $a->addDumper('ini', new \Symfony\Component\Translation\Dumper\IniFileDumper());
        $a->addDumper('json', new \Symfony\Component\Translation\Dumper\JsonFileDumper());
        $a->addDumper('res', new \Symfony\Component\Translation\Dumper\IcuResFileDumper());

        $container->privates['console.command.translation_update'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationUpdateCommand($a, ($container->privates['translation.reader'] ?? $container->load('getTranslation_ReaderService')), ($container->privates['translation.extractor'] ?? $container->load('getTranslation_ExtractorService')), 'en', 'C:\\my-project/translations', 'C:\\my-project/templates', [0 => 'C:\\my-project\\vendor\\symfony\\validator/Resources/translations', 1 => 'C:\\my-project\\vendor\\symfony\\form/Resources/translations', 2 => 'C:\\my-project\\vendor\\symfony\\security-core/Resources/translations'], [0 => 'C:\\my-project\\vendor\\symfony\\twig-bridge/Resources/views/Email', 1 => 'C:\\my-project\\vendor\\symfony\\twig-bridge/Resources/views/Form', 2 => 'C:\\my-project\\vendor\\symfony\\framework-bundle\\Command\\TranslationDebugCommand.php', 3 => 'C:\\my-project\\vendor\\symfony\\form\\Extension\\Core\\Type\\FileType.php', 4 => 'C:\\my-project\\vendor\\symfony\\form\\Extension\\Core\\Type\\ColorType.php', 5 => 'C:\\my-project\\vendor\\symfony\\form\\Extension\\Core\\Type\\TransformationFailureExtension.php', 6 => 'C:\\my-project\\vendor\\symfony\\form\\Extension\\Validator\\Type\\UploadValidatorExtension.php', 7 => 'C:\\my-project\\vendor\\symfony\\form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension.php', 8 => 'C:\\my-project\\vendor\\symfony\\validator\\ValidatorBuilder.php', 9 => 'C:\\my-project\\vendor\\symfony\\framework-bundle\\CacheWarmer\\TranslationsCacheWarmer.php', 10 => 'C:\\my-project\\vendor\\symfony\\translation\\DataCollector\\TranslationDataCollector.php', 11 => 'C:\\my-project\\vendor\\symfony\\twig-bridge\\Extension\\TranslationExtension.php']);

        $instance->setName('translation:update');

        return $instance;
    }
}
