<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerROGiq9o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerROGiq9o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerROGiq9o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerROGiq9o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerROGiq9o\App_KernelDevDebugContainer([
    'container.build_hash' => 'ROGiq9o',
    'container.build_id' => '80f2582e',
    'container.build_time' => 1593009326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerROGiq9o');
