<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBgOBkvP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBgOBkvP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBgOBkvP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBgOBkvP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBgOBkvP\App_KernelDevDebugContainer([
    'container.build_hash' => 'BgOBkvP',
    'container.build_id' => 'e27e13e6',
    'container.build_time' => 1593078992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBgOBkvP');
